import { useCallback } from "react";
import ReactFlow, { Background, Controls, ReactFlowProvider } from "reactflow";
import "reactflow/dist/style.css";
import { Button } from "../../../components/ui/button";
import { useAIAssistantStore } from "../../../stores/aiAssistantStore";
import IconComponent from "../../common/genericIconComponent";
import useFlowsManagerStore from "../../../stores/flowsManagerStore";
import { useToast } from "../../../components/ui/use-toast";

export default function FlowPreview() {
  const { toast } = useToast();
  const { flowNodes, flowEdges, instruction } = useAIAssistantStore();
  const { addFlow } = useFlowsManagerStore();

  const handleImportFlow = useCallback(() => {
    if (flowNodes.length === 0) {
      toast({
        title: "No flow to import",
        description: "Please build a flow first",
        variant: "destructive",
      });
      return;
    }

    try {
      // Create a new flow with the generated nodes and edges
      const newFlow = {
        name: `AI Generated Flow - ${new Date().toLocaleString()}`,
        description: instruction || "Generated by AI Assistant",
        data: {
          nodes: flowNodes,
          edges: flowEdges,
        },
      };

      // Add the flow to the flows manager
      addFlow(newFlow);

      toast({
        title: "Flow imported successfully",
        description: "The flow has been added to your flows",
      });
    } catch (error) {
      toast({
        title: "Error importing flow",
        description: error instanceof Error ? error.message : "Unknown error",
        variant: "destructive",
      });
    }
  }, [flowNodes, flowEdges, instruction, addFlow, toast]);

  return (
    <div className="flex h-full flex-col gap-4">
      <div className="flex-1 rounded-md border border-border">
        {flowNodes.length === 0 ? (
          <div className="flex h-full flex-col items-center justify-center text-center text-muted-foreground">
            <IconComponent name="FileFlow" className="mb-2 h-12 w-12" />
            <p>No flow preview available</p>
            <p className="text-sm">Build a flow from the Instruction tab</p>
          </div>
        ) : (
          <ReactFlowProvider>
            <ReactFlow
              nodes={flowNodes}
              edges={flowEdges}
              fitView
              attributionPosition="bottom-right"
              zoomOnScroll={false}
              panOnScroll={true}
              nodesDraggable={false}
              nodesConnectable={false}
              elementsSelectable={false}
              proOptions={{ hideAttribution: true }}
            >
              <Background />
              <Controls showInteractive={false} />
            </ReactFlow>
          </ReactFlowProvider>
        )}
      </div>

      <div className="flex items-center justify-between">
        <div className="text-sm text-muted-foreground">
          {flowNodes.length > 0
            ? `${flowNodes.length} nodes, ${flowEdges.length} connections`
            : "No flow data"}
        </div>

        <Button
          onClick={handleImportFlow}
          disabled={flowNodes.length === 0}
          variant="default"
        >
          <IconComponent name="Import" className="mr-2 h-4 w-4" />
          Import Flow
        </Button>
      </div>
    </div>
  );
}
