"""add_crm_indexes

Revision ID: 325df5b9eb02
Revises: 4d4f8a88110d
Create Date: 2025-05-23 15:18:05.123235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '325df5b9eb02'
down_revision: Union[str, None] = '4d4f8a88110d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_client_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_status'), ['status'], unique=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_invoice_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_issue_date'), ['issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_status'), ['status'], unique=False)

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_opportunity_expected_close_date'), ['expected_close_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_status'), ['status'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_task_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_priority'))
        batch_op.drop_index(batch_op.f('ix_task_due_date'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_status'))
        batch_op.drop_index(batch_op.f('ix_opportunity_expected_close_date'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_issue_date'))
        batch_op.drop_index(batch_op.f('ix_invoice_due_date'))
        batch_op.drop_index(batch_op.f('ix_invoice_amount'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_status'))
        batch_op.drop_index(batch_op.f('ix_client_email'))
        batch_op.drop_index(batch_op.f('ix_client_company'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
